export {default as IconReplay} from "./IconReplay"
export {default as IconExplore} from "./IconExplore"
export {default as IconStar} from "./IconStar"
export {default as IconEye} from "./IconEye"
export {default as IconAdd} from "./IconAdd"
export {default as IconStudy} from "./IconStudy"
export {default as IconCancel} from "./IconCancel"
export {default as IconCheck} from "./IconCheck"